-- Authoritative verified Git object bytes are independent of every interpretation.
CREATE TABLE git_object_payloads(
 git_object_id INTEGER PRIMARY KEY REFERENCES git_objects(git_object_id),
 payload_representation TEXT NOT NULL CHECK(payload_representation='git-object-raw-v1'),
 payload_sha256 BLOB NOT NULL CHECK(length(payload_sha256)=32),
 FOREIGN KEY(payload_representation,payload_sha256) REFERENCES payloads(representation,sha256)
) STRICT;
CREATE TRIGGER git_object_payloads_immutable BEFORE UPDATE ON git_object_payloads BEGIN SELECT RAISE(ABORT,'immutable Git bytes'); END;
CREATE TRIGGER git_object_payloads_retain BEFORE DELETE ON git_object_payloads BEGIN SELECT RAISE(ABORT,'retain Git bytes'); END;
CREATE TRIGGER git_object_payloads_no_replace BEFORE INSERT ON git_object_payloads WHEN EXISTS(SELECT 1 FROM git_object_payloads WHERE git_object_id=NEW.git_object_id) BEGIN SELECT RAISE(ABORT,'immutable Git bytes conflict'); END;
CREATE TRIGGER git_object_payloads_length BEFORE INSERT ON git_object_payloads WHEN NOT EXISTS(SELECT 1 FROM git_objects g JOIN stored_bytes b ON b.sha256=NEW.payload_sha256 WHERE g.git_object_id=NEW.git_object_id AND g.size=b.byte_length) BEGIN SELECT RAISE(ABORT,'Git raw payload length mismatch'); END;

CREATE TABLE git_text_facts(
 git_fact_uuidv4 TEXT PRIMARY KEY NOT NULL,
 parsed_result_uuidv4 TEXT NOT NULL, repository_uuidv4 TEXT NOT NULL, git_acquisition_id TEXT NOT NULL,
 git_object_id INTEGER NOT NULL REFERENCES git_objects(git_object_id), content_id INTEGER NOT NULL REFERENCES contents(content_id),
 text_state TEXT NOT NULL CHECK(text_state IN ('eligible','nul','non_utf8','oversize','unknown')), raw_text TEXT,
 UNIQUE(parsed_result_uuidv4,git_object_id),
 FOREIGN KEY(parsed_result_uuidv4,repository_uuidv4) REFERENCES parsed_results(parsed_result_uuidv4,repository_uuidv4),
 FOREIGN KEY(git_acquisition_id,repository_uuidv4) REFERENCES git_acquisitions(git_acquisition_id,repository_uuidv4),
 FOREIGN KEY(repository_uuidv4,git_object_id,git_acquisition_id) REFERENCES repository_object_sources(repository_uuidv4,git_object_id,git_acquisition_id)
) STRICT;
CREATE TRIGGER git_text_facts_content BEFORE INSERT ON git_text_facts WHEN NOT EXISTS(SELECT 1 FROM blob_content_map b WHERE b.git_object_id=NEW.git_object_id AND b.content_id=NEW.content_id) OR (NEW.raw_text IS NOT NULL AND NEW.text_state<>'eligible') BEGIN SELECT RAISE(ABORT,'Git text requires matching raw content identity'); END;
CREATE TRIGGER contents_immutable BEFORE UPDATE ON contents BEGIN SELECT RAISE(ABORT,'immutable raw content identity'); END;
CREATE TRIGGER contents_no_replace BEFORE INSERT ON contents WHEN EXISTS(SELECT 1 FROM contents WHERE content_id=NEW.content_id) BEGIN SELECT RAISE(ABORT,'immutable content identity conflict'); END;
CREATE TRIGGER contents_retain BEFORE DELETE ON contents BEGIN SELECT RAISE(ABORT,'retain content identity'); END;

CREATE INDEX commits_result_owner ON commits(parsed_result_uuidv4,repository_uuidv4);
CREATE TRIGGER commits_uuid4 BEFORE INSERT ON commits WHEN NOT(length(NEW.git_fact_uuidv4)=36 AND length(CAST(NEW.git_fact_uuidv4 AS BLOB))=36 AND substr(NEW.git_fact_uuidv4,9,1)='-' AND substr(NEW.git_fact_uuidv4,14,1)='-' AND substr(NEW.git_fact_uuidv4,19,1)='-' AND substr(NEW.git_fact_uuidv4,24,1)='-' AND length(replace(NEW.git_fact_uuidv4,'-',''))=32 AND replace(NEW.git_fact_uuidv4,'-','') NOT GLOB '*[^0-9a-f]*' AND substr(NEW.git_fact_uuidv4,15,1)='4' AND substr(NEW.git_fact_uuidv4,20,1) IN ('8','9','a','b')) BEGIN SELECT RAISE(ABORT,'invalid RFC UUIDv4'); END;
CREATE TRIGGER commits_input BEFORE INSERT ON commits WHEN NOT EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.repository_uuidv4=NEW.repository_uuidv4 AND i.git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'Git fact acquisition absent from result inputs'); END;
CREATE TRIGGER commits_capability BEFORE INSERT ON commits WHEN NOT EXISTS(SELECT 1 FROM parsed_results r JOIN parser_profile_capabilities c USING(parser_profile_uuidv4) WHERE r.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND c.owner_kind='repository' AND c.fact_kind='git') BEGIN SELECT RAISE(ABORT,'profile cannot emit Git facts'); END;
CREATE TRIGGER commits_sealed BEFORE INSERT ON commits WHEN EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=NEW.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'published parsed fact set is sealed'); END;
CREATE TRIGGER commits_no_replace BEFORE INSERT ON commits WHEN EXISTS(SELECT 1 FROM commits WHERE git_fact_uuidv4=NEW.git_fact_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git fact identity conflict'); END;
CREATE TRIGGER commits_retain BEFORE DELETE ON commits BEGIN SELECT RAISE(ABORT,'retain immutable Git interpretation'); END;
CREATE TRIGGER commits_immutable BEFORE UPDATE ON commits BEGIN SELECT RAISE(ABORT,'immutable Git interpretation'); END;
CREATE VIEW eligible_git_commits AS SELECT d.* FROM commits d JOIN usable_parsed_results r USING(parsed_result_uuidv4) JOIN effective_repository_parser_profiles p ON p.repository_uuidv4=d.repository_uuidv4 AND p.fact_kind='git' AND p.parser_profile_uuidv4=r.parser_profile_uuidv4;
CREATE VIEW current_git_commits AS SELECT d.* FROM eligible_git_commits d JOIN active_fact_selections f ON f.parsed_result_uuidv4=d.parsed_result_uuidv4 AND f.repository_uuidv4=d.repository_uuidv4 AND f.fact_kind='git' AND f.git_acquisition_id IS NULL;

CREATE INDEX commit_parents_result_owner ON commit_parents(parsed_result_uuidv4,repository_uuidv4);
CREATE TRIGGER commit_parents_uuid4 BEFORE INSERT ON commit_parents WHEN NOT(length(NEW.git_fact_uuidv4)=36 AND length(CAST(NEW.git_fact_uuidv4 AS BLOB))=36 AND substr(NEW.git_fact_uuidv4,9,1)='-' AND substr(NEW.git_fact_uuidv4,14,1)='-' AND substr(NEW.git_fact_uuidv4,19,1)='-' AND substr(NEW.git_fact_uuidv4,24,1)='-' AND length(replace(NEW.git_fact_uuidv4,'-',''))=32 AND replace(NEW.git_fact_uuidv4,'-','') NOT GLOB '*[^0-9a-f]*' AND substr(NEW.git_fact_uuidv4,15,1)='4' AND substr(NEW.git_fact_uuidv4,20,1) IN ('8','9','a','b')) BEGIN SELECT RAISE(ABORT,'invalid RFC UUIDv4'); END;
CREATE TRIGGER commit_parents_input BEFORE INSERT ON commit_parents WHEN NOT EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.repository_uuidv4=NEW.repository_uuidv4 AND i.git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'Git fact acquisition absent from result inputs'); END;
CREATE TRIGGER commit_parents_capability BEFORE INSERT ON commit_parents WHEN NOT EXISTS(SELECT 1 FROM parsed_results r JOIN parser_profile_capabilities c USING(parser_profile_uuidv4) WHERE r.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND c.owner_kind='repository' AND c.fact_kind='git') BEGIN SELECT RAISE(ABORT,'profile cannot emit Git facts'); END;
CREATE TRIGGER commit_parents_sealed BEFORE INSERT ON commit_parents WHEN EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=NEW.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'published parsed fact set is sealed'); END;
CREATE TRIGGER commit_parents_no_replace BEFORE INSERT ON commit_parents WHEN EXISTS(SELECT 1 FROM commit_parents WHERE git_fact_uuidv4=NEW.git_fact_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git fact identity conflict'); END;
CREATE TRIGGER commit_parents_retain BEFORE DELETE ON commit_parents BEGIN SELECT RAISE(ABORT,'retain immutable Git interpretation'); END;
CREATE TRIGGER commit_parents_immutable BEFORE UPDATE ON commit_parents BEGIN SELECT RAISE(ABORT,'immutable Git interpretation'); END;
CREATE VIEW eligible_git_commit_parents AS SELECT d.* FROM commit_parents d JOIN usable_parsed_results r USING(parsed_result_uuidv4) JOIN effective_repository_parser_profiles p ON p.repository_uuidv4=d.repository_uuidv4 AND p.fact_kind='git' AND p.parser_profile_uuidv4=r.parser_profile_uuidv4;
CREATE VIEW current_git_commit_parents AS SELECT d.* FROM eligible_git_commit_parents d JOIN active_fact_selections f ON f.parsed_result_uuidv4=d.parsed_result_uuidv4 AND f.repository_uuidv4=d.repository_uuidv4 AND f.fact_kind='git' AND f.git_acquisition_id IS NULL;

CREATE INDEX tree_entries_result_owner ON tree_entries(parsed_result_uuidv4,repository_uuidv4);
CREATE TRIGGER tree_entries_uuid4 BEFORE INSERT ON tree_entries WHEN NOT(length(NEW.git_fact_uuidv4)=36 AND length(CAST(NEW.git_fact_uuidv4 AS BLOB))=36 AND substr(NEW.git_fact_uuidv4,9,1)='-' AND substr(NEW.git_fact_uuidv4,14,1)='-' AND substr(NEW.git_fact_uuidv4,19,1)='-' AND substr(NEW.git_fact_uuidv4,24,1)='-' AND length(replace(NEW.git_fact_uuidv4,'-',''))=32 AND replace(NEW.git_fact_uuidv4,'-','') NOT GLOB '*[^0-9a-f]*' AND substr(NEW.git_fact_uuidv4,15,1)='4' AND substr(NEW.git_fact_uuidv4,20,1) IN ('8','9','a','b')) BEGIN SELECT RAISE(ABORT,'invalid RFC UUIDv4'); END;
CREATE TRIGGER tree_entries_input BEFORE INSERT ON tree_entries WHEN NOT EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.repository_uuidv4=NEW.repository_uuidv4 AND i.git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'Git fact acquisition absent from result inputs'); END;
CREATE TRIGGER tree_entries_capability BEFORE INSERT ON tree_entries WHEN NOT EXISTS(SELECT 1 FROM parsed_results r JOIN parser_profile_capabilities c USING(parser_profile_uuidv4) WHERE r.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND c.owner_kind='repository' AND c.fact_kind='git') BEGIN SELECT RAISE(ABORT,'profile cannot emit Git facts'); END;
CREATE TRIGGER tree_entries_sealed BEFORE INSERT ON tree_entries WHEN EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=NEW.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'published parsed fact set is sealed'); END;
CREATE TRIGGER tree_entries_no_replace BEFORE INSERT ON tree_entries WHEN EXISTS(SELECT 1 FROM tree_entries WHERE git_fact_uuidv4=NEW.git_fact_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git fact identity conflict'); END;
CREATE TRIGGER tree_entries_retain BEFORE DELETE ON tree_entries BEGIN SELECT RAISE(ABORT,'retain immutable Git interpretation'); END;
CREATE TRIGGER tree_entries_immutable BEFORE UPDATE ON tree_entries BEGIN SELECT RAISE(ABORT,'immutable Git interpretation'); END;
CREATE VIEW eligible_git_tree_entries AS SELECT d.* FROM tree_entries d JOIN usable_parsed_results r USING(parsed_result_uuidv4) JOIN effective_repository_parser_profiles p ON p.repository_uuidv4=d.repository_uuidv4 AND p.fact_kind='git' AND p.parser_profile_uuidv4=r.parser_profile_uuidv4;
CREATE VIEW current_git_tree_entries AS SELECT d.* FROM eligible_git_tree_entries d JOIN active_fact_selections f ON f.parsed_result_uuidv4=d.parsed_result_uuidv4 AND f.repository_uuidv4=d.repository_uuidv4 AND f.fact_kind='git' AND f.git_acquisition_id IS NULL;

CREATE INDEX tag_objects_result_owner ON tag_objects(parsed_result_uuidv4,repository_uuidv4);
CREATE TRIGGER tag_objects_uuid4 BEFORE INSERT ON tag_objects WHEN NOT(length(NEW.git_fact_uuidv4)=36 AND length(CAST(NEW.git_fact_uuidv4 AS BLOB))=36 AND substr(NEW.git_fact_uuidv4,9,1)='-' AND substr(NEW.git_fact_uuidv4,14,1)='-' AND substr(NEW.git_fact_uuidv4,19,1)='-' AND substr(NEW.git_fact_uuidv4,24,1)='-' AND length(replace(NEW.git_fact_uuidv4,'-',''))=32 AND replace(NEW.git_fact_uuidv4,'-','') NOT GLOB '*[^0-9a-f]*' AND substr(NEW.git_fact_uuidv4,15,1)='4' AND substr(NEW.git_fact_uuidv4,20,1) IN ('8','9','a','b')) BEGIN SELECT RAISE(ABORT,'invalid RFC UUIDv4'); END;
CREATE TRIGGER tag_objects_input BEFORE INSERT ON tag_objects WHEN NOT EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.repository_uuidv4=NEW.repository_uuidv4 AND i.git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'Git fact acquisition absent from result inputs'); END;
CREATE TRIGGER tag_objects_capability BEFORE INSERT ON tag_objects WHEN NOT EXISTS(SELECT 1 FROM parsed_results r JOIN parser_profile_capabilities c USING(parser_profile_uuidv4) WHERE r.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND c.owner_kind='repository' AND c.fact_kind='git') BEGIN SELECT RAISE(ABORT,'profile cannot emit Git facts'); END;
CREATE TRIGGER tag_objects_sealed BEFORE INSERT ON tag_objects WHEN EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=NEW.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'published parsed fact set is sealed'); END;
CREATE TRIGGER tag_objects_no_replace BEFORE INSERT ON tag_objects WHEN EXISTS(SELECT 1 FROM tag_objects WHERE git_fact_uuidv4=NEW.git_fact_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git fact identity conflict'); END;
CREATE TRIGGER tag_objects_retain BEFORE DELETE ON tag_objects BEGIN SELECT RAISE(ABORT,'retain immutable Git interpretation'); END;
CREATE TRIGGER tag_objects_immutable BEFORE UPDATE ON tag_objects BEGIN SELECT RAISE(ABORT,'immutable Git interpretation'); END;
CREATE VIEW eligible_git_tag_objects AS SELECT d.* FROM tag_objects d JOIN usable_parsed_results r USING(parsed_result_uuidv4) JOIN effective_repository_parser_profiles p ON p.repository_uuidv4=d.repository_uuidv4 AND p.fact_kind='git' AND p.parser_profile_uuidv4=r.parser_profile_uuidv4;
CREATE VIEW current_git_tag_objects AS SELECT d.* FROM eligible_git_tag_objects d JOIN active_fact_selections f ON f.parsed_result_uuidv4=d.parsed_result_uuidv4 AND f.repository_uuidv4=d.repository_uuidv4 AND f.fact_kind='git' AND f.git_acquisition_id IS NULL;

CREATE INDEX root_manifests_result_owner ON root_manifests(parsed_result_uuidv4,repository_uuidv4);
CREATE TRIGGER root_manifests_uuid4 BEFORE INSERT ON root_manifests WHEN NOT(length(NEW.git_fact_uuidv4)=36 AND length(CAST(NEW.git_fact_uuidv4 AS BLOB))=36 AND substr(NEW.git_fact_uuidv4,9,1)='-' AND substr(NEW.git_fact_uuidv4,14,1)='-' AND substr(NEW.git_fact_uuidv4,19,1)='-' AND substr(NEW.git_fact_uuidv4,24,1)='-' AND length(replace(NEW.git_fact_uuidv4,'-',''))=32 AND replace(NEW.git_fact_uuidv4,'-','') NOT GLOB '*[^0-9a-f]*' AND substr(NEW.git_fact_uuidv4,15,1)='4' AND substr(NEW.git_fact_uuidv4,20,1) IN ('8','9','a','b')) BEGIN SELECT RAISE(ABORT,'invalid RFC UUIDv4'); END;
CREATE TRIGGER root_manifests_input BEFORE INSERT ON root_manifests WHEN NOT EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.repository_uuidv4=NEW.repository_uuidv4 AND i.git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'Git fact acquisition absent from result inputs'); END;
CREATE TRIGGER root_manifests_capability BEFORE INSERT ON root_manifests WHEN NOT EXISTS(SELECT 1 FROM parsed_results r JOIN parser_profile_capabilities c USING(parser_profile_uuidv4) WHERE r.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND c.owner_kind='repository' AND c.fact_kind='git') BEGIN SELECT RAISE(ABORT,'profile cannot emit Git facts'); END;
CREATE TRIGGER root_manifests_sealed BEFORE INSERT ON root_manifests WHEN EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=NEW.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'published parsed fact set is sealed'); END;
CREATE TRIGGER root_manifests_no_replace BEFORE INSERT ON root_manifests WHEN EXISTS(SELECT 1 FROM root_manifests WHERE git_fact_uuidv4=NEW.git_fact_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git fact identity conflict'); END;
CREATE TRIGGER root_manifests_retain BEFORE DELETE ON root_manifests BEGIN SELECT RAISE(ABORT,'retain immutable Git interpretation'); END;
CREATE TRIGGER root_manifests_immutable BEFORE UPDATE ON root_manifests WHEN NEW.git_fact_uuidv4 IS NOT OLD.git_fact_uuidv4 OR NEW.parsed_result_uuidv4 IS NOT OLD.parsed_result_uuidv4 OR NEW.repository_uuidv4 IS NOT OLD.repository_uuidv4 OR NEW.git_acquisition_id IS NOT OLD.git_acquisition_id OR NEW.tree_git_object_id IS NOT OLD.tree_git_object_id OR NEW.complete<OLD.complete OR EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=OLD.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git manifest'); END;
CREATE VIEW eligible_git_root_manifests AS SELECT d.* FROM root_manifests d JOIN usable_parsed_results r USING(parsed_result_uuidv4) JOIN effective_repository_parser_profiles p ON p.repository_uuidv4=d.repository_uuidv4 AND p.fact_kind='git' AND p.parser_profile_uuidv4=r.parser_profile_uuidv4;
CREATE VIEW current_git_root_manifests AS SELECT d.* FROM eligible_git_root_manifests d JOIN active_fact_selections f ON f.parsed_result_uuidv4=d.parsed_result_uuidv4 AND f.repository_uuidv4=d.repository_uuidv4 AND f.fact_kind='git' AND f.git_acquisition_id IS NULL;

CREATE INDEX root_manifest_entries_result_owner ON root_manifest_entries(parsed_result_uuidv4,repository_uuidv4);
CREATE TRIGGER root_manifest_entries_uuid4 BEFORE INSERT ON root_manifest_entries WHEN NOT(length(NEW.git_fact_uuidv4)=36 AND length(CAST(NEW.git_fact_uuidv4 AS BLOB))=36 AND substr(NEW.git_fact_uuidv4,9,1)='-' AND substr(NEW.git_fact_uuidv4,14,1)='-' AND substr(NEW.git_fact_uuidv4,19,1)='-' AND substr(NEW.git_fact_uuidv4,24,1)='-' AND length(replace(NEW.git_fact_uuidv4,'-',''))=32 AND replace(NEW.git_fact_uuidv4,'-','') NOT GLOB '*[^0-9a-f]*' AND substr(NEW.git_fact_uuidv4,15,1)='4' AND substr(NEW.git_fact_uuidv4,20,1) IN ('8','9','a','b')) BEGIN SELECT RAISE(ABORT,'invalid RFC UUIDv4'); END;
CREATE TRIGGER root_manifest_entries_input BEFORE INSERT ON root_manifest_entries WHEN NOT EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.repository_uuidv4=NEW.repository_uuidv4 AND i.git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'Git fact acquisition absent from result inputs'); END;
CREATE TRIGGER root_manifest_entries_capability BEFORE INSERT ON root_manifest_entries WHEN NOT EXISTS(SELECT 1 FROM parsed_results r JOIN parser_profile_capabilities c USING(parser_profile_uuidv4) WHERE r.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND c.owner_kind='repository' AND c.fact_kind='git') BEGIN SELECT RAISE(ABORT,'profile cannot emit Git facts'); END;
CREATE TRIGGER root_manifest_entries_sealed BEFORE INSERT ON root_manifest_entries WHEN EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=NEW.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'published parsed fact set is sealed'); END;
CREATE TRIGGER root_manifest_entries_no_replace BEFORE INSERT ON root_manifest_entries WHEN EXISTS(SELECT 1 FROM root_manifest_entries WHERE git_fact_uuidv4=NEW.git_fact_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git fact identity conflict'); END;
CREATE TRIGGER root_manifest_entries_retain BEFORE DELETE ON root_manifest_entries BEGIN SELECT RAISE(ABORT,'retain immutable Git interpretation'); END;
CREATE TRIGGER root_manifest_entries_immutable BEFORE UPDATE ON root_manifest_entries BEGIN SELECT RAISE(ABORT,'immutable Git interpretation'); END;
CREATE VIEW eligible_git_root_manifest_entries AS SELECT d.* FROM root_manifest_entries d JOIN usable_parsed_results r USING(parsed_result_uuidv4) JOIN effective_repository_parser_profiles p ON p.repository_uuidv4=d.repository_uuidv4 AND p.fact_kind='git' AND p.parser_profile_uuidv4=r.parser_profile_uuidv4;
CREATE VIEW current_git_root_manifest_entries AS SELECT d.* FROM eligible_git_root_manifest_entries d JOIN active_fact_selections f ON f.parsed_result_uuidv4=d.parsed_result_uuidv4 AND f.repository_uuidv4=d.repository_uuidv4 AND f.fact_kind='git' AND f.git_acquisition_id IS NULL;

CREATE INDEX git_text_facts_result_owner ON git_text_facts(parsed_result_uuidv4,repository_uuidv4);
CREATE TRIGGER git_text_facts_uuid4 BEFORE INSERT ON git_text_facts WHEN NOT(length(NEW.git_fact_uuidv4)=36 AND length(CAST(NEW.git_fact_uuidv4 AS BLOB))=36 AND substr(NEW.git_fact_uuidv4,9,1)='-' AND substr(NEW.git_fact_uuidv4,14,1)='-' AND substr(NEW.git_fact_uuidv4,19,1)='-' AND substr(NEW.git_fact_uuidv4,24,1)='-' AND length(replace(NEW.git_fact_uuidv4,'-',''))=32 AND replace(NEW.git_fact_uuidv4,'-','') NOT GLOB '*[^0-9a-f]*' AND substr(NEW.git_fact_uuidv4,15,1)='4' AND substr(NEW.git_fact_uuidv4,20,1) IN ('8','9','a','b')) BEGIN SELECT RAISE(ABORT,'invalid RFC UUIDv4'); END;
CREATE TRIGGER git_text_facts_input BEFORE INSERT ON git_text_facts WHEN NOT EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.repository_uuidv4=NEW.repository_uuidv4 AND i.git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'Git fact acquisition absent from result inputs'); END;
CREATE TRIGGER git_text_facts_capability BEFORE INSERT ON git_text_facts WHEN NOT EXISTS(SELECT 1 FROM parsed_results r JOIN parser_profile_capabilities c USING(parser_profile_uuidv4) WHERE r.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND c.owner_kind='repository' AND c.fact_kind='git') BEGIN SELECT RAISE(ABORT,'profile cannot emit Git facts'); END;
CREATE TRIGGER git_text_facts_sealed BEFORE INSERT ON git_text_facts WHEN EXISTS(SELECT 1 FROM parsed_result_publications WHERE parsed_result_uuidv4=NEW.parsed_result_uuidv4) BEGIN SELECT RAISE(ABORT,'published parsed fact set is sealed'); END;
CREATE TRIGGER git_text_facts_no_replace BEFORE INSERT ON git_text_facts WHEN EXISTS(SELECT 1 FROM git_text_facts WHERE git_fact_uuidv4=NEW.git_fact_uuidv4) BEGIN SELECT RAISE(ABORT,'immutable Git fact identity conflict'); END;
CREATE TRIGGER git_text_facts_retain BEFORE DELETE ON git_text_facts BEGIN SELECT RAISE(ABORT,'retain immutable Git interpretation'); END;
CREATE TRIGGER git_text_facts_immutable BEFORE UPDATE ON git_text_facts BEGIN SELECT RAISE(ABORT,'immutable Git interpretation'); END;
CREATE VIEW eligible_git_text_facts AS SELECT d.* FROM git_text_facts d JOIN usable_parsed_results r USING(parsed_result_uuidv4) JOIN effective_repository_parser_profiles p ON p.repository_uuidv4=d.repository_uuidv4 AND p.fact_kind='git' AND p.parser_profile_uuidv4=r.parser_profile_uuidv4;
CREATE VIEW current_git_text_facts AS SELECT d.* FROM eligible_git_text_facts d JOIN active_fact_selections f ON f.parsed_result_uuidv4=d.parsed_result_uuidv4 AND f.repository_uuidv4=d.repository_uuidv4 AND f.fact_kind='git' AND f.git_acquisition_id IS NULL;
CREATE TRIGGER commits_object_type BEFORE INSERT ON commits WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.git_object_id AND type='commit') BEGIN SELECT RAISE(ABORT,'Git fact object type mismatch'); END;
CREATE TRIGGER root_manifests_object_type BEFORE INSERT ON root_manifests WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.tree_git_object_id AND type='tree') BEGIN SELECT RAISE(ABORT,'Git fact object type mismatch'); END;
CREATE TRIGGER tree_entries_object_type BEFORE INSERT ON tree_entries WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.tree_git_object_id AND type='tree') BEGIN SELECT RAISE(ABORT,'Git fact object type mismatch'); END;
CREATE TRIGGER tag_objects_object_type BEFORE INSERT ON tag_objects WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.git_object_id AND type='tag') BEGIN SELECT RAISE(ABORT,'Git fact object type mismatch'); END;
CREATE TRIGGER git_text_facts_object_type BEFORE INSERT ON git_text_facts WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.git_object_id AND type='blob') BEGIN SELECT RAISE(ABORT,'Git fact object type mismatch'); END;
CREATE TRIGGER commit_parents_object_type BEFORE INSERT ON commit_parents WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.parent_git_object_id AND type='commit') BEGIN SELECT RAISE(ABORT,'Git fact object type mismatch'); END;
CREATE TRIGGER commits_tree_type BEFORE INSERT ON commits WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.tree_git_object_id AND type='tree') BEGIN SELECT RAISE(ABORT,'commit tree type mismatch'); END;
CREATE TRIGGER tree_entries_child_identity BEFORE INSERT ON tree_entries WHEN NEW.child_git_object_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.child_git_object_id AND object_format=NEW.child_format AND oid=NEW.child_oid AND type=CASE NEW.mode WHEN 16384 THEN 'tree' ELSE 'blob' END) BEGIN SELECT RAISE(ABORT,'tree child identity/type mismatch'); END;
CREATE TRIGGER root_manifest_entries_child_identity BEFORE INSERT ON root_manifest_entries WHEN NEW.git_object_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.git_object_id AND object_format=NEW.object_format AND oid=NEW.oid AND type='blob') BEGIN SELECT RAISE(ABORT,'manifest child identity/type mismatch'); END;

-- An acquisition has its own explicit immutable interpretation selection.
-- This preserves recorded/PR contexts independently of the current ref snapshot.
CREATE VIEW selected_git_acquisition_results AS
SELECT f.repository_uuidv4,f.git_acquisition_id,f.parsed_result_uuidv4
FROM active_fact_selections f WHERE f.fact_kind='git' AND f.git_acquisition_id IS NOT NULL;
CREATE TRIGGER commits_formats BEFORE INSERT ON commits WHEN NOT EXISTS(SELECT 1 FROM git_objects a JOIN git_objects b ON b.git_object_id=NEW.tree_git_object_id WHERE a.git_object_id=NEW.git_object_id AND a.object_format=b.object_format) BEGIN SELECT RAISE(ABORT,'commit/tree object format mismatch'); END;
CREATE TRIGGER commit_parents_formats BEFORE INSERT ON commit_parents WHEN NOT EXISTS(SELECT 1 FROM git_objects a JOIN git_objects b ON b.git_object_id=NEW.parent_git_object_id WHERE a.git_object_id=NEW.commit_git_object_id AND a.object_format=b.object_format) BEGIN SELECT RAISE(ABORT,'commit parent object format mismatch'); END;
CREATE TRIGGER tag_objects_formats BEFORE INSERT ON tag_objects WHEN NOT EXISTS(SELECT 1 FROM git_objects a JOIN git_objects b ON b.git_object_id=NEW.target_git_object_id WHERE a.git_object_id=NEW.git_object_id AND a.object_format=b.object_format) BEGIN SELECT RAISE(ABORT,'tag object format mismatch'); END;
CREATE TRIGGER tree_entries_formats BEFORE INSERT ON tree_entries WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.tree_git_object_id AND object_format=NEW.child_format) BEGIN SELECT RAISE(ABORT,'tree child object format mismatch'); END;
CREATE TRIGGER root_manifest_entries_formats BEFORE INSERT ON root_manifest_entries WHEN NOT EXISTS(SELECT 1 FROM git_objects WHERE git_object_id=NEW.tree_git_object_id AND object_format=NEW.object_format) BEGIN SELECT RAISE(ABORT,'manifest child object format mismatch'); END;

-- The exact object membership of an acquired input becomes immutable with its
-- first published interpretation. Reparse reuses that same acquired byte set.
CREATE TRIGGER parsed_publication_git_bytes BEFORE INSERT ON parsed_result_publications
WHEN EXISTS(SELECT 1 FROM parsed_result_inputs i JOIN repository_object_sources r ON r.git_acquisition_id=i.git_acquisition_id AND r.repository_uuidv4=i.repository_uuidv4 LEFT JOIN git_object_payloads b USING(git_object_id) WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND b.git_object_id IS NULL)
BEGIN SELECT RAISE(ABORT,'Git publication requires every acquired raw object payload'); END;

-- A Git input names its exact immutable byte/object and traversal-root set.
-- Missing reception of any member cannot masquerade as a complete empty input.
CREATE TABLE git_acquisition_publications(
 git_acquisition_id TEXT PRIMARY KEY NOT NULL,
 repository_uuidv4 TEXT NOT NULL,
 object_manifest_json TEXT NOT NULL CHECK(json_valid(object_manifest_json) AND json_type(object_manifest_json)='array'),
 root_manifest_json TEXT NOT NULL CHECK(json_valid(root_manifest_json) AND json_type(root_manifest_json)='array'),
 FOREIGN KEY(git_acquisition_id,repository_uuidv4) REFERENCES git_acquisitions(git_acquisition_id,repository_uuidv4)
) STRICT;
CREATE TRIGGER git_acquisition_publications_immutable BEFORE UPDATE ON git_acquisition_publications BEGIN SELECT RAISE(ABORT,'immutable Git acquisition byte membership'); END;
CREATE TRIGGER git_acquisition_publications_retain BEFORE DELETE ON git_acquisition_publications BEGIN SELECT RAISE(ABORT,'retain Git acquisition byte membership'); END;
CREATE TRIGGER git_acquisition_publications_no_replace BEFORE INSERT ON git_acquisition_publications WHEN EXISTS(SELECT 1 FROM git_acquisition_publications WHERE git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'immutable Git acquisition membership conflict'); END;
CREATE TRIGGER git_acquisition_publications_objects BEFORE INSERT ON git_acquisition_publications
WHEN json_array_length(NEW.object_manifest_json)<>(SELECT count(*) FROM repository_object_sources r WHERE r.git_acquisition_id=NEW.git_acquisition_id AND r.repository_uuidv4=NEW.repository_uuidv4)
 OR EXISTS(SELECT 1 FROM json_each(NEW.object_manifest_json) m WHERE coalesce(json_type(m.value),'')<>'object' OR (SELECT count(*) FROM json_each(m.value))<>3 OR coalesce(json_type(m.value,'$.object_format'),'')<>'text' OR coalesce(json_type(m.value,'$.oid'),'')<>'text' OR coalesce(json_type(m.value,'$.payload'),'')<>'object' OR (SELECT count(*) FROM json_each(m.value,'$.payload'))<>2 OR NOT EXISTS(SELECT 1 FROM repository_object_sources r JOIN git_objects g USING(git_object_id) JOIN git_object_payloads p USING(git_object_id) WHERE r.git_acquisition_id=NEW.git_acquisition_id AND r.repository_uuidv4=NEW.repository_uuidv4 AND g.object_format=json_extract(m.value,'$.object_format') AND lower(hex(g.oid))=json_extract(m.value,'$.oid') AND p.payload_representation=json_extract(m.value,'$.payload.representation') AND lower(hex(p.payload_sha256))=json_extract(m.value,'$.payload.sha256')))
 OR json_array_length(NEW.object_manifest_json)<>(SELECT count(*) FROM (SELECT DISTINCT json_extract(m.value,'$.object_format'),json_extract(m.value,'$.oid') FROM json_each(NEW.object_manifest_json) m))
BEGIN SELECT RAISE(ABORT,'Git acquired object manifest incomplete or invalid'); END;
CREATE TRIGGER git_acquisition_publications_roots BEFORE INSERT ON git_acquisition_publications
WHEN json_array_length(NEW.root_manifest_json)<>(SELECT count(*) FROM acquisition_roots r WHERE r.git_acquisition_id=NEW.git_acquisition_id AND r.repository_uuidv4=NEW.repository_uuidv4)
 OR EXISTS(SELECT 1 FROM json_each(NEW.root_manifest_json) m WHERE coalesce(json_type(m.value),'')<>'object' OR (SELECT count(*) FROM json_each(m.value))<>3 OR NOT EXISTS(SELECT 1 FROM acquisition_roots r WHERE r.git_acquisition_id=NEW.git_acquisition_id AND r.repository_uuidv4=NEW.repository_uuidv4 AND r.object_format=json_extract(m.value,'$.object_format') AND lower(hex(r.oid))=json_extract(m.value,'$.oid') AND r.role=json_extract(m.value,'$.role')))
 OR json_array_length(NEW.root_manifest_json)<>(SELECT count(*) FROM (SELECT DISTINCT json_extract(m.value,'$.object_format'),json_extract(m.value,'$.oid'),json_extract(m.value,'$.role') FROM json_each(NEW.root_manifest_json) m))
BEGIN SELECT RAISE(ABORT,'Git acquired root manifest incomplete or invalid'); END;
CREATE TRIGGER repository_object_sources_input_sealed BEFORE INSERT ON repository_object_sources WHEN EXISTS(SELECT 1 FROM git_acquisition_publications WHERE git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'published Git acquisition object set is sealed'); END;
CREATE TRIGGER acquisition_roots_input_sealed BEFORE INSERT ON acquisition_roots WHEN EXISTS(SELECT 1 FROM git_acquisition_publications WHERE git_acquisition_id=NEW.git_acquisition_id) BEGIN SELECT RAISE(ABORT,'published Git acquisition root set is sealed'); END;
CREATE TRIGGER parsed_publication_git_acquisition_manifest BEFORE INSERT ON parsed_result_publications WHEN EXISTS(SELECT 1 FROM parsed_result_inputs i WHERE i.parsed_result_uuidv4=NEW.parsed_result_uuidv4 AND i.git_acquisition_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM git_acquisition_publications g WHERE g.git_acquisition_id=i.git_acquisition_id AND g.repository_uuidv4=i.repository_uuidv4)) BEGIN SELECT RAISE(ABORT,'Git input acquisition membership publication is missing'); END;
CREATE TRIGGER git_acquisition_publications_root_membership BEFORE INSERT ON git_acquisition_publications
WHEN EXISTS(SELECT 1 FROM acquisition_roots a WHERE a.git_acquisition_id=NEW.git_acquisition_id AND NOT EXISTS(SELECT 1 FROM repository_object_sources r JOIN git_objects g USING(git_object_id) WHERE r.git_acquisition_id=NEW.git_acquisition_id AND r.repository_uuidv4=NEW.repository_uuidv4 AND g.object_format=a.object_format AND g.oid=a.oid))
BEGIN SELECT RAISE(ABORT,'Git traversal root missing from acquired object membership'); END;
