query RepoCatalogThreadComments($thread: ID!, $commentCursor: String, $pageSize: Int!) {
  node(id: $thread) {
    ... on PullRequestReviewThread {
      id
      comments(first: $pageSize, after: $commentCursor) {
        nodes { id fullDatabaseId body url updatedAt author { login } pullRequestReview { fullDatabaseId } replyTo { fullDatabaseId } position originalPosition commit { oid } originalCommit { oid } path line originalLine diffHunk }
        pageInfo { hasNextPage endCursor }
      }
    }
  }
}
